# Generated by Django 4.2.16 on 2026-04-12 18:00

import apps.projects.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membre projet',
                'verbose_name_plural': 'Membres projet',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Commentaire')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.projects.models.task_attachment_path, verbose_name='Fichier joint')),
                ('audio', models.FileField(blank=True, null=True, upload_to=apps.projects.models.task_attachment_path, verbose_name='Mémo vocal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commentaire de tâche',
                'verbose_name_plural': 'Commentaires de tâches',
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_status_f023cb_idx',
            old_name='projects_pr_status_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_referen_43c609_idx',
            old_name='projects_pr_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_manager_6dc9b1_idx',
            old_name='projects_pr_manager_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='projects_ta_status_d6b74c_idx',
            old_name='projects_ta_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='projects_ta_phase_i_211b78_idx',
            old_name='projects_ta_phase_order_idx',
        ),
        migrations.AddField(
            model_name='project',
            name='initial_order',
            field=models.FileField(blank=True, help_text='PDF, Word ou image du marché ou bon de commande signé.', null=True, upload_to='projets/commandes/', verbose_name='Commande / Marché initial'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.task', verbose_name='Tâche'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_additions', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'user')},
        ),
    ]
