# Generated by Django 4.2.16 on 2026-04-12 22:27

import apps.projects.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_projectmember_taskcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='Date début prévue')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='Date fin prévue')),
                ('notes', models.TextField(blank=True, verbose_name='Instructions chantier')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef_chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers_chef', to=settings.AUTH_USER_MODEL, verbose_name='Chef de chantier')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installation_plan', to='projects.project', verbose_name='Projet')),
                ('team_members', models.ManyToManyField(blank=True, related_name='pose_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Équipe de pose')),
            ],
            options={
                'verbose_name': 'Plan de pose',
                'verbose_name_plural': 'Plans de pose',
            },
        ),
        migrations.CreateModel(
            name='InstallationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(verbose_name='Semaine')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('date_report', models.DateField(auto_now_add=True, verbose_name='Date du rapport')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Avancement (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Avancement / Travaux réalisés')),
                ('difficulties', models.TextField(blank=True, verbose_name='Difficultés rencontrées')),
                ('incident', models.BooleanField(default=False, verbose_name='Incident signalé')),
                ('incident_description', models.TextField(blank=True, verbose_name='Description incident')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.projects.models.pose_photo_path, verbose_name='Photo chantier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_reports', to='projects.project', verbose_name='Projet')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pose_reports', to=settings.AUTH_USER_MODEL, verbose_name='Rédigé par')),
            ],
            options={
                'verbose_name': 'Rapport de pose',
                'verbose_name_plural': 'Rapports de pose',
                'ordering': ['-year', '-week_number'],
                'unique_together': {('project', 'week_number', 'year')},
            },
        ),
    ]
