# Generated by Django 4.2.16 on 2026-04-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_installationplan_installationreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin projet'), ('EDITEUR', 'Éditeur'), ('VALIDATEUR', 'Validateur'), ('LECTEUR', 'Lecteur')], default='EDITEUR', max_length=20, verbose_name='Rôle sur le projet'),
        ),
    ]
