# Generated by Django 4.2.16 on 2026-04-16 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chiffrage', '0001_initial'),
        ('projects', '0004_projectmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='owner_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='phase',
            name='partie',
            field=models.CharField(blank=True, max_length=1, verbose_name='Partie (A/B/C)'),
        ),
        migrations.AddField(
            model_name='phase',
            name='planned_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fin prévue'),
        ),
        migrations.AddField(
            model_name='phase',
            name='planned_start',
            field=models.DateField(blank=True, null=True, verbose_name='Début prévu'),
        ),
        migrations.AddField(
            model_name='phasetemplate',
            name='owner_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='phasetemplate',
            name='partie',
            field=models.CharField(blank=True, max_length=1, verbose_name='Partie (A/B/C)'),
        ),
        migrations.AddField(
            model_name='project',
            name='demande_chiffrage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projet', to='chiffrage.demandechiffrage', verbose_name='Demande de chiffrage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget (MAD)'),
        ),
    ]
