# Generated by Django 4.2.16 on 2026-04-17 17:00

import apps.projects.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_phase_owner_label_phase_partie_phase_planned_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Message')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.projects.models.phase_comment_path, verbose_name='Pièce jointe')),
                ('audio', models.FileField(blank=True, null=True, upload_to=apps.projects.models.phase_comment_path, verbose_name='Mémo vocal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_comments', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.phase', verbose_name='Phase')),
            ],
            options={
                'verbose_name': 'Commentaire de phase',
                'verbose_name_plural': 'Commentaires de phases',
                'ordering': ['created_at'],
            },
        ),
    ]
