# Generated by Django 4.2.16 on 2026-04-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_phase_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Avancement (%)'),
        ),
    ]
