# Generated by Django 4.2.16 on 2026-04-22 15:00

import apps.projects.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_phase_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Message')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.projects.models.project_message_path, verbose_name='Pièce jointe')),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('audio', models.FileField(blank=True, null=True, upload_to=apps.projects.models.project_message_path, verbose_name='Mémo vocal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_messages', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projects.project', verbose_name='Projet')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='projects.projectmessage', verbose_name='Réponse à')),
            ],
            options={
                'verbose_name': 'Message projet',
                'verbose_name_plural': 'Messages projet',
                'ordering': ['created_at'],
            },
        ),
    ]
