# Generated by Django 4.2.16 on 2026-04-23 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_projectmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'étape")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('responsables_roles', models.JSONField(default=list, help_text='Liste de codes de rôle ex: ["ADV","COMMERCIAL"]', verbose_name='Rôles responsables')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminée')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminée le')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_steps', to=settings.AUTH_USER_MODEL, verbose_name='Terminée par')),
            ],
            options={
                'verbose_name': 'Étape projet',
                'verbose_name_plural': 'Étapes projet',
                'ordering': ['project', 'order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='chef_de_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_diriges', to=settings.AUTH_USER_MODEL, verbose_name='Chef de projet'),
        ),
        migrations.AddField(
            model_name='project',
            name='chef_designe_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Désigné le'),
        ),
        migrations.AddField(
            model_name='project',
            name='chef_designe_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_designes', to=settings.AUTH_USER_MODEL, verbose_name='Désigné par'),
        ),
        migrations.AddField(
            model_name='project',
            name='chef_valide_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validé le'),
        ),
        migrations.AddField(
            model_name='project',
            name='chef_valide_par_admin',
            field=models.BooleanField(default=False, verbose_name='Validé par admin'),
        ),
        migrations.CreateModel(
            name='StepComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Commentaire')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='projets/step_comments/', verbose_name='Pièce jointe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_comments', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projectstep', verbose_name='Étape')),
            ],
            options={
                'verbose_name': "Commentaire d'étape",
                'verbose_name_plural': "Commentaires d'étapes",
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectstep',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='projects.project', verbose_name='Projet'),
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Commentaire')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='projets/comments/', verbose_name='Pièce jointe')),
                ('audio', models.FileField(blank=True, null=True, upload_to='projets/comments/', verbose_name='Mémo vocal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_comments_authored', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Commentaire projet',
                'verbose_name_plural': 'Commentaires projet',
                'ordering': ['created_at'],
            },
        ),
    ]
