# Generated by Django 4.2.16 on 2026-06-25 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_projectstep_project_chef_de_projet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecompteProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence projet')),
                ('client_name', models.CharField(max_length=200, verbose_name='Client')),
                ('nom_projet', models.CharField(blank=True, max_length=300, verbose_name='Intitulé projet')),
                ('montant_marche_ht', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Montant Marché HT')),
                ('lot', models.CharField(blank=True, max_length=100, verbose_name='Lot')),
                ('adjudication', models.BooleanField(default=False, verbose_name='Adjudication')),
                ('regime', models.CharField(choices=[('AVEC_TVA', 'Avec TVA'), ('SANS_TVA', 'Sans TVA')], default='AVEC_TVA', max_length=10, verbose_name='Régime TVA')),
                ('init_attachement', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Cumul attachement initial')),
                ('init_rg', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Cumul RG initial')),
                ('init_rf', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Cumul RF initial')),
                ('init_prorata', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Cumul prorata initial')),
                ('init_acompte', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Acompte initial')),
                ('init_reglements', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Cumul règlements initial')),
                ('init_liv_systeme', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Liv. système initiale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef_de_projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decomptes_chef', to=settings.AUTH_USER_MODEL, verbose_name='Chef de projet')),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decomptes_commercial', to=settings.AUTH_USER_MODEL, verbose_name='Commercial')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decomptes_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Projet décompte',
                'verbose_name_plural': 'Projets décompte',
                'ordering': ['client_name', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='DecompteLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_decompte', models.CharField(blank=True, max_length=50, verbose_name='N° Décompte')),
                ('type_operation', models.CharField(choices=[('DECOMPTE', 'Décompte'), ('SITUATION', 'Situation'), ('FACTURE', 'Facture finale'), ('AVOIR', 'Avoir')], default='DECOMPTE', max_length=20, verbose_name='Type opération')),
                ('date_edition_facture', models.DateField(blank=True, null=True, verbose_name='Date édition facture')),
                ('ref_piece', models.CharField(blank=True, max_length=100, verbose_name='Réf. Pièce')),
                ('attachement', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Attachement')),
                ('prorata', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Prorata')),
                ('rg', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='RG')),
                ('rf', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='RF')),
                ('autre', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Autre')),
                ('amortissement_acompte', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Amortissement acompte')),
                ('acompte', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Acompte')),
                ('ht', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='HT')),
                ('reglement', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Règlement')),
                ('liv_systeme', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Liv. Système')),
                ('semaine', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Semaine')),
                ('annee', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année')),
                ('is_dernier_decompte', models.BooleanField(default=False, verbose_name='Dernier décompte actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decompte_lignes', to='projects.decompteprojet', verbose_name='Projet')),
                ('saisie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decomptes_saisis', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
            ],
            options={
                'verbose_name': 'Ligne de décompte',
                'verbose_name_plural': 'Lignes de décompte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecompteAvenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Montant HT (MAD)')),
                ('date_avenant', models.DateField(blank=True, null=True, verbose_name="Date de l'avenant")),
                ('reference_doc', models.CharField(blank=True, max_length=100, verbose_name='Référence document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avenants_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avenants_decompte', to='projects.decompteprojet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Avenant',
                'verbose_name_plural': 'Avenants',
                'ordering': ['date_avenant'],
            },
        ),
    ]
