# Generated by Django 4.2.16 on 2026-04-15 07:59

import apps.chiffrage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeChiffrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Référence')),
                ('client_nom', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_ref_affaire', models.CharField(blank=True, max_length=100, verbose_name='Référence affaire')),
                ('description', models.TextField(verbose_name='Description commerciale')),
                ('delai_souhaite', models.DateField(blank=True, null=True, verbose_name='Délai souhaité')),
                ('urgence', models.CharField(choices=[('STANDARD', 'Standard'), ('URGENT', 'Urgent'), ('CRITIQUE', 'Critique')], default='STANDARD', max_length=10, verbose_name='Urgence')),
                ('finitions', models.TextField(blank=True, verbose_name='Finitions souhaitées')),
                ('kits_references', models.TextField(blank=True, verbose_name='Kits / références produits')),
                ('quantites_estimees', models.TextField(blank=True, verbose_name='Quantités estimées')),
                ('contraintes_techniques', models.TextField(blank=True, verbose_name='Contraintes techniques')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires libres')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation DC'), ('VALIDEE_DC', 'Validée — En attente Méthodes'), ('REJETEE', 'Rejetée — À corriger'), ('RETOURNEE', 'Retournée pour complétion'), ('EN_CHIFFRAGE', 'En cours de chiffrage'), ('SOUMIS_DG', 'Soumis à la DG'), ('REVISION_DG', 'En révision — Retour DG'), ('DEVIS_VALIDE', 'Devis validé'), ('TRANSMIS', 'Transmis au client'), ('ACCEPTE', 'Accepté par le client'), ('REFUSE_CLI', 'Refusé par le client'), ('ARCHIVE', 'Archivé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('jalon', models.CharField(blank=True, choices=[('ANALYSE', 'Analyse en cours'), ('CHIFFRAGE', 'Chiffrage en cours'), ('REVISION', 'En révision interne')], max_length=20, verbose_name='Jalon Méthodes')),
                ('montant_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant HT (MAD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_dc_at', models.DateTimeField(blank=True, null=True)),
                ('validated_dg_at', models.DateTimeField(blank=True, null=True)),
                ('transmis_client_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiffrages_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Chiffreur assigné')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chiffrages_soumis', to=settings.AUTH_USER_MODEL, verbose_name='Commercial')),
                ('validated_by_dc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiffrages_valides_dc', to=settings.AUTH_USER_MODEL, verbose_name='Validé par DC')),
                ('validated_by_dg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiffrages_valides_dg', to=settings.AUTH_USER_MODEL, verbose_name='Validé par DG')),
            ],
            options={
                'verbose_name': 'Demande de chiffrage',
                'verbose_name_plural': 'Demandes de chiffrage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageFil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to=apps.chiffrage.models.message_file_path)),
                ('nom_fichier', models.CharField(blank=True, max_length=255)),
                ('is_internal', models.BooleanField(default=False, verbose_name='Note interne (invisible commercial)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiffrage_messages', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chiffrage.demandechiffrage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150)),
                ('detail', models.TextField(blank=True)),
                ('ancien_statut', models.CharField(blank=True, max_length=20)),
                ('nouveau_statut', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiffrage_historique', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='chiffrage.demandechiffrage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FichierChiffrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=apps.chiffrage.models.chiffrage_file_path)),
                ('nom', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('taille', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=False, verbose_name='Interne (invisible commercial)')),
                ('is_devis', models.BooleanField(default=False, verbose_name='Fichier devis final')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='chiffrage.demandechiffrage')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiffrage_fichiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.TextField(verbose_name='Nature de la modification')),
                ('justification', models.TextField(verbose_name='Justification')),
                ('urgence', models.CharField(choices=[('STANDARD', 'Standard'), ('URGENT', 'Urgent'), ('CRITIQUE', 'Critique')], default='STANDARD', max_length=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'arbitrage"), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=10)),
                ('motif_refus', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traite_at', models.DateTimeField(blank=True, null=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_modification', to='chiffrage.demandechiffrage')),
                ('soumis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_soumises', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='demandechiffrage',
            index=models.Index(fields=['statut'], name='chiffrage_d_statut_d8f829_idx'),
        ),
        migrations.AddIndex(
            model_name='demandechiffrage',
            index=models.Index(fields=['commercial'], name='chiffrage_d_commerc_b4319d_idx'),
        ),
        migrations.AddIndex(
            model_name='demandechiffrage',
            index=models.Index(fields=['urgence'], name='chiffrage_d_urgence_5a21ec_idx'),
        ),
    ]
