# Generated by Django 4.2.16 on 2026-04-21 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_activity_model'),
        ('chiffrage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandechiffrage',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiffrages', to='crm.lead', verbose_name='Opportunité CRM'),
        ),
    ]
