# Generated by Django 4.2.16 on 2026-05-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiffrage', '0002_add_lead_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichierchiffrage',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Devis sans détail (visible DC/Commercial après validation DG)'),
        ),
        migrations.AlterField(
            model_name='demandechiffrage',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation DC'), ('VALIDEE_DC', 'Validée — En attente Méthodes'), ('REJETEE', 'Rejetée — À corriger'), ('RETOURNEE', 'Retournée pour complétion'), ('EN_CHIFFRAGE', 'En cours de chiffrage'), ('SOUMIS_RM', 'Soumis au Responsable Méthodes'), ('SOUMIS_DG', 'Soumis à la DG'), ('REVISION_DG', 'En révision — Retour DG'), ('DEVIS_VALIDE', 'Devis validé'), ('TRANSMIS', 'Transmis au client'), ('ACCEPTE', 'Accepté par le client'), ('REFUSE_CLI', 'Refusé par le client'), ('ARCHIVE', 'Archivé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
    ]
