# Generated by Django 4.2.16 on 2026-06-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiffrage', '0003_add_is_public_to_fichierchiffrage'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandechiffrage',
            name='lien_telechargement',
            field=models.URLField(blank=True, max_length=500, verbose_name='Lien de téléchargement'),
        ),
    ]
