# Generated by Django 4.2.16 on 2026-06-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiffrage', '0004_add_lien_telechargement'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandechiffrage',
            name='revision_commentaire_dc',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire DC (révision)'),
        ),
        migrations.AddField(
            model_name='demandechiffrage',
            name='revision_motif',
            field=models.TextField(blank=True, default='', verbose_name='Motif de révision'),
        ),
        migrations.AlterField(
            model_name='demandechiffrage',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation DC'), ('VALIDEE_DC', 'Validée — En attente Méthodes'), ('REJETEE', 'Rejetée — À corriger'), ('RETOURNEE', 'Retournée pour complétion'), ('EN_CHIFFRAGE', 'En cours de chiffrage'), ('SOUMIS_RM', 'Soumis au Responsable Méthodes'), ('SOUMIS_DG', 'Soumis à la DG'), ('REVISION_DG', 'En révision — Retour DG'), ('DEVIS_VALIDE', 'Devis validé'), ('TRANSMIS', 'Transmis au client'), ('ACCEPTE', 'Accepté par le client'), ('REFUSE_CLI', 'Refusé par le client'), ('ARCHIVE', 'Archivé'), ('REVISION_DEMANDEE', 'Révision demandée — En attente DC'), ('REVISION_INFO_DC', 'Révision — Informations complémentaires demandées')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
    ]
