# Generated by Django 4.2.16 on 2026-04-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_project_22a9a9_idx',
            old_name='documents_doc_proj_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_is_late_165124_idx',
            old_name='documents_doc_latest_idx',
        ),
    ]
