# Generated by Django 4.2.16 on 2026-04-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTEUR', 'Directeur'), ('MANAGER', 'Manager'), ('ESTIMATEUR', 'Estimateur'), ('COMMERCIAL', 'Commercial'), ('ATELIER', 'Atelier'), ('CHAUFFEUR', 'Chauffeur'), ('POSEUR', 'Poseur')], default='MANAGER', max_length=20, verbose_name='Rôle'),
        ),
    ]
