# Generated by Django 4.2.16 on 2026-04-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTEUR', 'Directeur Général (DG)'), ('MANAGER', 'Directeur Commercial (DC)'), ('ESTIMATEUR', 'Méthodes / Estimateur'), ('COMMERCIAL', 'Commercial'), ('ATELIER', 'Atelier'), ('CHAUFFEUR', 'Chauffeur'), ('POSEUR', 'Poseur')], default='MANAGER', max_length=20, verbose_name='Rôle'),
        ),
    ]
