# Generated by Django 4.2.16 on 2026-04-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DIRECTEUR', 'Directeur Général (DG)'), ('MANAGER', 'Directeur Commercial (DC)'), ('ESTIMATEUR', 'Méthodes / Estimateur'), ('COMMERCIAL', 'Commercial'), ('ADV', 'ADV'), ('ATELIER', 'Usine'), ('CHAUFFEUR', 'Logistique'), ('POSEUR', 'Poseur'), ('FINANCE', 'Finance'), ('SAV', 'SAV')], default='MANAGER', max_length=20, verbose_name='Rôle'),
        ),
    ]
