# Generated by Django 4.2.16 on 2026-04-12 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_installationplan_installationreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Contact')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Entreprise')),
                ('client_type', models.CharField(blank=True, help_text='Promoteur, Hôtel, Particulier, Bureau...', max_length=100, verbose_name='Type de client')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('project_name', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('project_type', models.CharField(blank=True, help_text='Résidentiel, Hôtel, Bureaux...', max_length=100, verbose_name='Type de projet')),
                ('products', models.CharField(blank=True, help_text='Portes, Placards, Cuisines...', max_length=300, verbose_name='Produits concernés')),
                ('potential', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('IMPORTANT', 'Important')], default='MOYEN', max_length=20, verbose_name='Potentiel')),
                ('canal_origine', models.CharField(blank=True, choices=[('APPEL_ENTRANT', 'Appel entrant'), ('PRESCRIPTION', 'Prescription'), ('SALON', 'Salon / Expo'), ('APPEL_OFFRE', "Appel d'offre"), ('RECOMMANDATION', 'Recommandation'), ('VISITE_TERRAIN', 'Visite terrain'), ('AUTRE', 'Autre')], max_length=30, verbose_name="Canal d'origine")),
                ('flux_type', models.CharField(blank=True, choices=[('COMMANDE', 'Commande directe'), ('MARCHE', 'Marché (AO)')], max_length=20, verbose_name='Type de flux')),
                ('status', models.CharField(choices=[('VISITE', 'Visite'), ('OPPORTUNITE', 'Opportunité'), ('QUALIFICATION', 'Qualification'), ('CHIFFRAGE', 'Chiffrage'), ('OFFRE', 'Offre envoyée'), ('GAGNEE', 'Gagnée'), ('PERDUE', 'Perdue')], default='VISITE', max_length=20, verbose_name='Statut')),
                ('next_followup_date', models.DateField(blank=True, null=True, verbose_name='Prochaine relance')),
                ('budget_mad', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Budget (MAD)')),
                ('nb_logements', models.IntegerField(blank=True, null=True, verbose_name='Nb logements / unités')),
                ('start_date_est', models.DateField(blank=True, null=True, verbose_name='Début estimé')),
                ('end_date_est', models.DateField(blank=True, null=True, verbose_name='Fin estimée')),
                ('probability', models.CharField(blank=True, choices=[('LOW', '< 30 %'), ('MED', '30 – 70 %'), ('HIGH', '> 70 %')], max_length=10, verbose_name='Probabilité')),
                ('competitor', models.CharField(blank=True, max_length=300, verbose_name='Concurrent(s)')),
                ('strategic_comment', models.TextField(blank=True, verbose_name='Commentaire stratégique')),
                ('offer_amount_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant offre HT (MAD)')),
                ('offer_sent_date', models.DateField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('offer_validity_days', models.IntegerField(default=30, verbose_name='Validité (jours)')),
                ('loss_reason', models.CharField(blank=True, choices=[('PRIX', 'Prix'), ('DELAI', 'Délai'), ('CONCURRENT', 'Concurrent retenu'), ('ANNULE', 'Projet annulé'), ('TECHNIQUE', 'Faisabilité technique'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Motif perte')),
                ('loss_notes', models.TextField(blank=True, verbose_name='Notes perte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='projects.project', verbose_name='Dossier projet')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Note lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
