# Generated by Django 4.2.16 on 2026-04-21 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('VISITE', 'Visite terrain'), ('APPEL', 'Appel téléphonique'), ('REUNION', 'Réunion'), ('DEMO', 'Démonstration'), ('RELANCE', 'Relance'), ('EMAIL', 'Email')], max_length=20, verbose_name='Type')),
                ('subject', models.CharField(max_length=200, verbose_name='Objet')),
                ('planned_at', models.DateTimeField(verbose_name='Date / heure prévue')),
                ('duration_min', models.PositiveSmallIntegerField(default=60, verbose_name='Durée (min)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('status', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('REALISE', 'Réalisé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20, verbose_name='Statut')),
                ('compte_rendu', models.TextField(blank=True, verbose_name='Compte rendu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to=settings.AUTH_USER_MODEL, verbose_name='Commercial')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead', verbose_name='Opportunité')),
            ],
            options={
                'verbose_name': 'Activité CRM',
                'verbose_name_plural': 'Activités CRM',
                'ordering': ['planned_at'],
            },
        ),
    ]
