# Generated by Django 4.2.16 on 2026-04-21 10:07

import apps.crm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_activity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('appointment_type', models.CharField(choices=[('DECOUVERTE', 'Découverte'), ('TECHNIQUE', 'Technique'), ('PROPOSITION', 'Présentation offre'), ('SUIVI', 'Suivi'), ('VISITE', 'Visite chantier')], default='DECOUVERTE', max_length=20, verbose_name='Type')),
                ('scheduled_at', models.DateTimeField(verbose_name='Date / heure')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='Durée (min)')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Lieu')),
                ('status', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('REALISE', 'Réalisé'), ('ANNULE', 'Annulé'), ('REPORTE', 'Reporté')], default='PLANIFIE', max_length=20, verbose_name='Statut')),
                ('report', models.TextField(blank=True, verbose_name='Compte rendu')),
                ('report_written_at', models.DateTimeField(blank=True, null=True, verbose_name='Compte rendu rédigé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='crm_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='detailed_needs',
            field=models.TextField(blank=True, verbose_name='Besoins détaillés'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('DIRECTOR_ASSIGNED', 'Assignée par le DC'), ('COMMERCIAL_CREATED', 'Créée par commercial')], default='DIRECTOR_ASSIGNED', max_length=30, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='lead',
            name='technical_notes',
            field=models.TextField(blank=True, verbose_name='Notes techniques'),
        ),
        migrations.AddField(
            model_name='lead',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validé le'),
        ),
        migrations.AddField(
            model_name='lead',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_leads', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='lead',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_VALIDATION', 'En attente de validation'), ('VALIDATED', 'Validée')], default='VALIDATED', max_length=30, verbose_name='Statut workflow'),
        ),
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PLAN', 'Plan'), ('TECH_SPEC', 'Cahier des charges'), ('PHOTO', 'Photo chantier'), ('MEETING_REPORT', 'Compte rendu'), ('OFFRE', 'Offre commerciale'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to=apps.crm.models.lead_document_path, verbose_name='Fichier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.appointment', verbose_name='RDV associé')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.lead', verbose_name='Opportunité')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_crm_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document lead',
                'verbose_name_plural': 'Documents leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('NOTE', 'Note'), ('APPEL', 'Appel'), ('EMAIL', 'Email'), ('STATUS_CHANGE', 'Changement statut'), ('ASSIGNMENT', 'Attribution'), ('VALIDATION', 'Validation'), ('DOCUMENT_ADDED', 'Document ajouté'), ('RDV_ADDED', 'RDV planifié'), ('RDV_DONE', 'RDV réalisé')], max_length=20, verbose_name='Type')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='crm.lead', verbose_name='Lead')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log activité lead',
                'verbose_name_plural': 'Logs activité leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='crm.lead', verbose_name='Opportunité'),
        ),
    ]
