# Generated by Django 4.2.16 on 2026-06-24 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0003_appointment_lead_detailed_needs_lead_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunitePipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200, verbose_name='Client')),
                ('projet', models.CharField(max_length=200, verbose_name='Projet')),
                ('segment', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Hospitality', 'Hospitality'), ('Institutional', 'Institutional'), ('Industrial & Logistics', 'Industrial & Logistics')], max_length=30, verbose_name='Segment')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('pays', models.CharField(default='Maroc', max_length=100, verbose_name='Pays')),
                ('potentiel_mad', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Potentiel (MAD)')),
                ('probabilite', models.CharField(blank=True, choices=[('0.10', '10 %'), ('0.50', '50 %'), ('0.80', '80 %'), ('1.00', '100 %')], default='', max_length=4, verbose_name='Probabilité')),
                ('commentaire_terrain', models.TextField(blank=True, verbose_name='Commentaire terrain')),
                ('statut', models.CharField(choices=[('Prospection', 'Prospection'), ('En cours', 'En cours'), ('Négociation', 'Négociation'), ('Gagné', 'Gagné'), ('Perdu', 'Perdu')], default='Prospection', max_length=20, verbose_name='Statut')),
                ('prochaine_action', models.CharField(blank=True, max_length=255, verbose_name='Prochaine action')),
                ('date_action', models.DateField(blank=True, null=True, verbose_name='Date action')),
                ('date_closing_est', models.DateField(blank=True, null=True, verbose_name='Date closing estimée')),
                ('risque', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, verbose_name='Risque')),
                ('derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunites_pipeline', to=settings.AUTH_USER_MODEL, verbose_name='Commercial')),
            ],
            options={
                'verbose_name': 'Opportunité Pipeline',
                'verbose_name_plural': 'Opportunités Pipeline',
                'ordering': ['-derniere_maj'],
            },
        ),
    ]
