# Generated by Django 4.2.16 on 2026-04-13 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_projectmember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseWorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configured_at', models.DateTimeField(auto_now_add=True)),
                ('require_validation', models.BooleanField(default=True, verbose_name='Bloquer sans validation')),
                ('configured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_wf_configs', to=settings.AUTH_USER_MODEL)),
                ('phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_config', to='projects.phase')),
            ],
            options={
                'verbose_name': 'Config workflow phase',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gabarit de workflow',
                'verbose_name_plural': 'Gabarits de workflow',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('approval_mode', models.CharField(choices=[('ANY', 'Un validateur suffit'), ('ALL', 'Tous doivent valider')], default='ANY', max_length=3)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflowtemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TaskWorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configured_at', models.DateTimeField(auto_now_add=True)),
                ('require_validation', models.BooleanField(default=True, verbose_name='Bloquer sans validation')),
                ('configured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_wf_configs', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_config', to='projects.task')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_configs', to='workflows.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Config workflow tâche',
            },
        ),
        migrations.CreateModel(
            name='StepValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validators', to='workflows.phaseworkflowconfig')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validators', to='workflows.workflowstep')),
                ('task_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validators', to='workflows.taskworkflowconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Validateur d'étape",
            },
        ),
        migrations.AddField(
            model_name='phaseworkflowconfig',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phase_configs', to='workflows.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step_order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='IN_PROGRESS', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_approvals', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='projects.phase')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='projects.task')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Demande de validation',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='workflows.approvalrequest')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.workflowstep')),
            ],
            options={
                'verbose_name': 'Décision',
                'ordering': ['decided_at'],
                'unique_together': {('request', 'step', 'decided_by')},
            },
        ),
    ]
