# Generated by Django 4.2.16 on 2026-04-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_4e3567_idx',
            old_name='notif_recipient_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_created_46ad24_idx',
            old_name='notif_created_at_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Tâche affectée'), ('TASK_ACTIVATED', 'Tâche activée'), ('TASK_COMPLETED', 'Tâche terminée'), ('TASK_OVERDUE', 'Tâche en retard'), ('PHASE_STARTED', 'Phase démarrée'), ('PHASE_DONE', 'Phase terminée'), ('PROJECT_UPDATE', 'Mise à jour projet'), ('DOCUMENT_ADDED', 'Document ajouté'), ('MENTION', 'Mention'), ('APPROVAL_REQUESTED', 'Validation requise'), ('APPROVAL_APPROVED', 'Approbation partielle'), ('APPROVAL_REJECTED', 'Validation rejetée'), ('APPROVAL_COMPLETED', 'Validation complète')], max_length=30, verbose_name='Type'),
        ),
    ]
